application: raincodejax
version: 2
runtime: php
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /index\.html
  static_files: index.html
  upload: index\.html

- url: /project\.html
  static_files: project.html
  upload: project\.html

- url: /math\.html
  static_files: math.html
  upload: math\.html

- url: /math1\.html
  static_files: math1.html
  upload: math1\.html

- url: /
  static_files: index.html
  upload: index\.html

- url: /style\.css
  static_files: style.css
  upload: style\.css

- url: /w/readme\.html
  static_files: w/readme.html
  upload: w/readme\.html
