application: jax-ml-45
version: 4
runtime: go
api_version: go1

handlers:
- url: (/get|/post|/put|/delete)
  script: _go_app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index\.html

- url: /index\.html
  static_files: index.html
  upload: index\.html

- url: /project\.html
  static_files: admin/project.html
  upload: admin/

- url: /math\.html
  static_files: d/math.html
  upload: d/

- url: /math1\.html
  static_files: d/math1.html
  upload: d/

- url: /SpecRunner.html
  static_files: t/SpecRunner.html
  upload: t/

- url: /google\-drive\.html
  static_files: d/google-drive.html
  upload: d/

- url: /s
  static_dir: s

- url: /t
  static_dir: t

- url: /l
  static_dir: l

- url: /d
  static_dir: d

- url: /v
  static_dir: review

- url: /w
  static_dir: review/w

- url: /a
  static_dir: admin
